version: '3'
services:
  notificationservice:
    build:
      context: .
    image: notificationservice
    networks:
    - notification
    ports:
    - 8085:8085
  mosquitto:
    image: eclipse-mosquitto:2.0.12
    ports:
      - "1884:1883"
    
networks:
     notification:
      external: true